name: M2
favicon: null
layout_spectrum: 0.48614
typography_spectrum: 0.1356033
style: the-composer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7FACE9'
    - '#FF645D'
    - '#16161F'
    - '#FFFFFA'
    - '#E6CF89'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
